-- posts table 
CREATE TABLE POSTS(
	ID SERIAL PRIMARY KEY, 
	TITLE TEXT NULL,
	CONTENT TEXT NULL,
	PARENT_ID INT NULL,
	AUTHOR_ID INT NULL,
	TYPE VARCHAR(100) NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- question_tags table
CREATE TABLE QUESTION_TAGS(
	QUESTION_ID INT NULL,
	TAG_ID INT NULL
);


-- tags table
CREATE TABLE TAGS(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(255) NULL
);

--users table
CREATE TABLE USERS(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(255) NULL,
	EMAIL VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NULL,
	TOKEN VARCHAR(255)
);


-- votes table
CREATE TABLE VOTES(
	ID SERIAL NOT NULL PRIMARY KEY,
	VOTE INT NULL,
	POST_ID INT NULL,
	USER_ID INT NULL
);


-- table user_tags
CREATE TABLE USER_TAGS(
	USER_ID INT NULL,
	TAG_ID INT NULL
);


-- insert queries for tags table
INSERT INTO TAGS (NAME) VALUES('JAVA');
INSERT INTO TAGS (NAME) VALUES('PYTHON');
INSERT INTO TAGS (NAME) VALUES('SQL');
INSERT INTO TAGS (NAME) VALUES('JAVASCRIPT');



